/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['AppController_getHello']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['HealthController_check']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/files/upload': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['UploadController_uploadFile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/files/uploads': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['UploadController_uploadFiles']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 用户登录 */
    post: operations['AuthController_login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 当前登录用户信息 */
    get: operations['AuthController_profile']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询用户列表 */
    get: operations['UserController_findAll']
    put?: never
    /** 创建用户 */
    post: operations['UserController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询用户详情 */
    get: operations['UserController_findOne']
    /** 更新用户 */
    put: operations['UserController_update']
    post?: never
    /** 删除用户 */
    delete: operations['UserController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/customers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询客户列表 */
    get: operations['CustomerController_findAll']
    put?: never
    /** 创建客户 */
    post: operations['CustomerController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/customers/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询客户详情 */
    get: operations['CustomerController_findOne']
    /** 更新客户 */
    put: operations['CustomerController_update']
    post?: never
    /** 删除客户（软删除） */
    delete: operations['CustomerController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/leads': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询线索列表 */
    get: operations['LeadController_findAll']
    put?: never
    /** 创建线索 */
    post: operations['LeadController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/leads/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询线索详情 */
    get: operations['LeadController_findOne']
    /** 更新线索 */
    put: operations['LeadController_update']
    post?: never
    /** 删除线索（软删除） */
    delete: operations['LeadController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/intentions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询意向列表 */
    get: operations['IntentionController_findAll']
    put?: never
    /** 创建意向 */
    post: operations['IntentionController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/intentions/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询意向详情 */
    get: operations['IntentionController_findOne']
    /** 更新意向 */
    put: operations['IntentionController_update']
    post?: never
    /** 删除意向（软删除） */
    delete: operations['IntentionController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/equipment': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询设备列表 */
    get: operations['EquipmentController_findAll']
    put?: never
    /** 创建设备 */
    post: operations['EquipmentController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/equipment/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询设备详情 */
    get: operations['EquipmentController_findOne']
    /** 更新设备 */
    put: operations['EquipmentController_update']
    post?: never
    /** 删除设备（软删除） */
    delete: operations['EquipmentController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tickets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询工单列表 */
    get: operations['TicketController_findAll']
    put?: never
    /** 创建工单 */
    post: operations['TicketController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tickets/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询工单详情 */
    get: operations['TicketController_findOne']
    /** 更新工单 */
    put: operations['TicketController_update']
    post?: never
    /** 删除工单（软删除） */
    delete: operations['TicketController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询任务列表 */
    get: operations['TaskController_findAll']
    put?: never
    /** 创建任务 */
    post: operations['TaskController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询任务详情 */
    get: operations['TaskController_findOne']
    /** 更新任务 */
    put: operations['TaskController_update']
    post?: never
    /** 删除任务（软删除） */
    delete: operations['TaskController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/approvals': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询审批列表 */
    get: operations['ApprovalController_findAll']
    put?: never
    /** 创建审批 */
    post: operations['ApprovalController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/approvals/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询审批详情 */
    get: operations['ApprovalController_findOne']
    /** 更新审批/审批操作 */
    put: operations['ApprovalController_update']
    post?: never
    /** 删除审批（软删除） */
    delete: operations['ApprovalController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/apps': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询应用列表 */
    get: operations['AppController_findAll']
    put?: never
    /** 创建应用 */
    post: operations['AppController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/apps/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询应用详情 */
    get: operations['AppController_findOne']
    /** 更新应用 */
    put: operations['AppController_update']
    post?: never
    /** 删除应用（软删除） */
    delete: operations['AppController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    LoginDto: {
      /** @description 用户名 */
      username: string
      /** @description 密码 */
      password: string
    }
    CreateUserDto: {
      /** @description 用户名 */
      username: string
      /** @description 密码 */
      password: string
      /** @description 姓名 */
      name: string
      /** @description 手机号 */
      phone?: string
      /** @description 邮箱 */
      email?: string
      /** @description 部门ID */
      departmentId?: string
      /** @description 角色ID数组 */
      roleIds?: string[]
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'ACTIVE' | 'INACTIVE'
    }
    UpdateUserDto: {
      /** @description 密码 */
      password?: string
      /** @description 姓名 */
      name?: string
      /** @description 手机号 */
      phone?: string
      /** @description 邮箱 */
      email?: string
      /** @description 部门ID */
      departmentId?: string
      /** @description 角色ID数组 */
      roleIds?: string[]
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'ACTIVE' | 'INACTIVE'
    }
    CreateCustomerDto: {
      /** @description 客户名称 */
      name: string
      /** @description 客户类型 */
      type: string
      /** @description 医院等级 */
      hospitalLevel?: string
      /**
       * @description 客户级别
       * @enum {string}
       */
      level?: 'STRATEGIC' | 'NORMAL'
      /** @description 健康评分 */
      healthScore?: number
      /** @description 所属区域 */
      region: string
      /** @description 区域ID */
      regionId?: string
      /** @description 地址信息 */
      address?: Record<string, never>
      /** @description 负责人ID */
      ownerId: string
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'POTENTIAL' | 'COOPERATING' | 'LOST'
      /** @description 标签数组 */
      tags?: string[]
      /** @description 来源 */
      source?: string
    }
    UpdateCustomerDto: {
      /** @description 客户名称 */
      name?: string
      /** @description 客户类型 */
      type?: string
      /** @description 医院等级 */
      hospitalLevel?: string
      /**
       * @description 客户级别
       * @enum {string}
       */
      level?: 'STRATEGIC' | 'NORMAL'
      /** @description 健康评分 */
      healthScore?: number
      /** @description 所属区域 */
      region?: string
      /** @description 区域ID */
      regionId?: string
      /** @description 地址信息 */
      address?: Record<string, never>
      /** @description 负责人ID */
      ownerId?: string
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'POTENTIAL' | 'COOPERATING' | 'LOST'
      /** @description 标签数组 */
      tags?: string[]
      /** @description 来源 */
      source?: string
    }
    CreateLeadDto: {
      /** @description 线索名称 */
      name: string
      /** @description 线索来源 */
      source: string
      /** @description 来源明细 */
      sourceDetail?: string
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'PENDING' | 'FOLLOWING' | 'CONVERTED' | 'INVALID'
      /**
       * @description 线索池类型
       * @enum {string}
       */
      poolType?: 'MINE' | 'PUBLIC' | 'TEAM'
      /** @description 负责人ID */
      ownerId?: string
      /** @description 所属区域 */
      region?: string
      /** @description 联系人姓名 */
      contactName?: string
      /** @description 联系人电话 */
      contactPhone?: string
      /** @description 公司名称 */
      companyName?: string
      /** @description 需求描述 */
      demand?: string
      /** @description 预计金额 */
      estimatedAmount?: number
      /**
       * @description 意向等级
       * @enum {string}
       */
      intentionLevel?: 'HIGH' | 'MEDIUM' | 'LOW'
    }
    UpdateLeadDto: {
      /** @description 线索名称 */
      name?: string
      /** @description 线索来源 */
      source?: string
      /** @description 来源明细 */
      sourceDetail?: string
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'PENDING' | 'FOLLOWING' | 'CONVERTED' | 'INVALID'
      /**
       * @description 线索池类型
       * @enum {string}
       */
      poolType?: 'MINE' | 'PUBLIC' | 'TEAM'
      /** @description 负责人ID */
      ownerId?: string
      /** @description 所属区域 */
      region?: string
      /** @description 联系人姓名 */
      contactName?: string
      /** @description 联系人电话 */
      contactPhone?: string
      /** @description 公司名称 */
      companyName?: string
      /** @description 需求描述 */
      demand?: string
      /** @description 预计金额 */
      estimatedAmount?: number
      /**
       * @description 意向等级
       * @enum {string}
       */
      intentionLevel?: 'HIGH' | 'MEDIUM' | 'LOW'
      /** @description 转化客户ID */
      convertedCustomerId?: string
    }
    CreateIntentionDto: {
      /** @description 客户ID */
      customerId: string
      /** @description 产品ID */
      productId?: string
      /** @description 预计金额 */
      amount?: number
      /**
       * @description 所处阶段
       * @enum {string}
       */
      stage?: 'INITIAL' | 'NEGOTIATION' | 'QUOTATION' | 'CONTRACT' | 'WON'
      /** @description 赢单概率 0-100 */
      probability?: number
      /** @description 预计成交时间 */
      expectedAt?: string
      /** @description 负责人ID */
      ownerId: string
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'ACTIVE' | 'WON' | 'LOST' | 'STALLED'
      /** @description 输单原因 */
      lostReason?: string
    }
    UpdateIntentionDto: {
      /** @description 客户ID */
      customerId?: string
      /** @description 产品ID */
      productId?: string
      /** @description 预计金额 */
      amount?: number
      /**
       * @description 所处阶段
       * @enum {string}
       */
      stage?: 'INITIAL' | 'NEGOTIATION' | 'QUOTATION' | 'CONTRACT' | 'WON'
      /** @description 赢单概率 0-100 */
      probability?: number
      /** @description 预计成交时间 */
      expectedAt?: string
      /** @description 负责人ID */
      ownerId?: string
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'ACTIVE' | 'WON' | 'LOST' | 'STALLED'
      /** @description 输单原因 */
      lostReason?: string
    }
    CreateEquipmentDto: {
      /** @description 设备编码 */
      code: string
      /** @description 设备名称 */
      name: string
      /** @description 产品ID */
      productId?: string
      /** @description 客户ID */
      customerId?: string
      /** @description 序列号 */
      serialNo?: string
      /** @description 装机日期 */
      installDate?: string
      /** @description 保修到期日 */
      warrantyExpire?: string
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'RUNNING' | 'MAINTAINING' | 'SCRAPPED'
      /** @description 负责人ID */
      ownerId?: string
    }
    UpdateEquipmentDto: {
      /** @description 设备编码 */
      code?: string
      /** @description 设备名称 */
      name?: string
      /** @description 产品ID */
      productId?: string
      /** @description 客户ID */
      customerId?: string
      /** @description 序列号 */
      serialNo?: string
      /** @description 装机日期 */
      installDate?: string
      /** @description 保修到期日 */
      warrantyExpire?: string
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'RUNNING' | 'MAINTAINING' | 'SCRAPPED'
      /** @description 负责人ID */
      ownerId?: string
    }
    CreateTicketDto: {
      /** @description 工单标题 */
      title: string
      /**
       * @description 工单类型
       * @enum {string}
       */
      type?: 'REPAIR' | 'MAINTENANCE' | 'CONSULT' | 'COMPLAINT'
      /**
       * @description 优先级
       * @enum {string}
       */
      priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT'
      /** @description 客户ID */
      customerId?: string
      /** @description 联系人ID */
      contactId?: string
      /** @description 设备ID */
      equipmentId?: string
      /** @description 报单人ID */
      reporterId: string
      /** @description 处理人ID */
      assigneeId?: string
      /**
       * @description 来源
       * @enum {string}
       */
      source?: 'PHONE' | 'WECHAT' | 'APP' | 'AGENT'
      /** @description 工单内容 */
      content: string
    }
    UpdateTicketDto: {
      /** @description 工单标题 */
      title?: string
      /**
       * @description 工单类型
       * @enum {string}
       */
      type?: 'REPAIR' | 'MAINTENANCE' | 'CONSULT' | 'COMPLAINT'
      /**
       * @description 优先级
       * @enum {string}
       */
      priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT'
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'PENDING' | 'PROCESSING' | 'WAITING' | 'RESOLVED' | 'CLOSED'
      /** @description 客户ID */
      customerId?: string
      /** @description 联系人ID */
      contactId?: string
      /** @description 设备ID */
      equipmentId?: string
      /** @description 处理人ID */
      assigneeId?: string
      /**
       * @description 来源
       * @enum {string}
       */
      source?: 'PHONE' | 'WECHAT' | 'APP' | 'AGENT'
      /** @description 工单内容 */
      content?: string
      /** @description 解决方案 */
      solution?: string
    }
    CreateTaskDto: {
      /** @description 任务标题 */
      title: string
      /** @description 任务内容 */
      content?: string
      /**
       * @description 任务类型
       * @enum {string}
       */
      type?: 'TODO' | 'FOLLOW_UP' | 'APPROVAL' | 'REVIEW'
      /**
       * @description 优先级
       * @enum {string}
       */
      priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT'
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED'
      /** @description 截止时间 */
      dueAt?: string
      /** @description 负责人ID */
      ownerId?: string
      /** @description 执行人ID列表 */
      assigneeIds?: string[]
      /** @description 参与人ID列表 */
      participantIds?: string[]
      /**
       * @description 关联业务类型
       * @enum {string}
       */
      relatedType?: 'CUSTOMER' | 'LEAD' | 'INTENTION' | 'TICKET'
      /** @description 关联业务ID */
      relatedId?: string
      /** @description 创建人ID */
      createdBy?: string
    }
    UpdateTaskDto: {
      /** @description 任务标题 */
      title?: string
      /** @description 任务内容 */
      content?: string
      /**
       * @description 任务类型
       * @enum {string}
       */
      type?: 'TODO' | 'FOLLOW_UP' | 'APPROVAL' | 'REVIEW'
      /**
       * @description 优先级
       * @enum {string}
       */
      priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT'
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED'
      /** @description 截止时间 */
      dueAt?: string
      /** @description 负责人ID */
      ownerId?: string
      /** @description 执行人ID列表 */
      assigneeIds?: string[]
      /** @description 参与人ID列表 */
      participantIds?: string[]
      /**
       * @description 关联业务类型
       * @enum {string}
       */
      relatedType?: 'CUSTOMER' | 'LEAD' | 'INTENTION' | 'TICKET'
      /** @description 关联业务ID */
      relatedId?: string
      /** @description 创建人ID */
      createdBy?: string
    }
    CreateApprovalDto: {
      /** @description 审批标题 */
      title: string
      /** @description 业务关键字 */
      businessKey?: string
      /** @description 审批模板编码 */
      templateCode?: string
      /**
       * @description 审批类型
       * @enum {string}
       */
      module?: 'leave' | 'expense' | 'contract' | 'discount' | 'purchase' | 'other'
      /** @description 表单数据 */
      payload?: Record<string, never>
      /** @description 抄送人ID列表 */
      ccUserIds?: string[]
    }
    UpdateApprovalDto: {
      /** @description 审批标题 */
      title?: string
      /** @description 业务关键字 */
      businessKey?: string
      /** @description 审批模板编码 */
      templateCode?: string
      /**
       * @description 审批类型
       * @enum {string}
       */
      module?: 'leave' | 'expense' | 'contract' | 'discount' | 'purchase' | 'other'
      /** @description 表单数据 */
      payload?: Record<string, never>
      /** @description 抄送人ID列表 */
      ccUserIds?: string[]
    }
    CreateAppDto: {
      /** @description 应用编码 */
      code: string
      /** @description 应用名称 */
      name: string
      /** @description 图标 */
      icon?: string
      /** @description 路由路径 */
      route?: string
      /**
       * @description 分类
       * @enum {string}
       */
      category?: 'PLATFORM' | 'BUSINESS' | 'PROCESS' | 'ANALYSIS' | 'SYSTEM'
      /** @description 权限列表 */
      permissions?: string[]
      /** @description 排序 */
      sortOrder?: number
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'ACTIVE' | 'INACTIVE'
    }
    UpdateAppDto: {
      /** @description 应用编码 */
      code?: string
      /** @description 应用名称 */
      name?: string
      /** @description 图标 */
      icon?: string
      /** @description 路由路径 */
      route?: string
      /**
       * @description 分类
       * @enum {string}
       */
      category?: 'PLATFORM' | 'BUSINESS' | 'PROCESS' | 'ANALYSIS' | 'SYSTEM'
      /** @description 权限列表 */
      permissions?: string[]
      /** @description 排序 */
      sortOrder?: number
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'ACTIVE' | 'INACTIVE'
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  HealthController_check: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UploadController_uploadFile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UploadController_uploadFiles: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_profile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_findAll: {
    parameters: {
      query: {
        page: number
        pageSize: number
        keyword: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserDto']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CustomerController_findAll: {
    parameters: {
      query?: {
        /** @description 页码 */
        page?: number
        /** @description 每页条数 */
        pageSize?: number
        /** @description 关键字（名称/标签） */
        keyword?: string
        /** @description 状态 */
        status?: 'POTENTIAL' | 'COOPERATING' | 'LOST'
        /** @description 客户级别 */
        level?: 'STRATEGIC' | 'NORMAL'
        /** @description 区域ID */
        regionId?: string
        /** @description 负责人ID */
        ownerId?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回分页客户列表 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CustomerController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCustomerDto']
      }
    }
    responses: {
      /** @description 创建成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CustomerController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回客户详情及关联数据 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CustomerController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCustomerDto']
      }
    }
    responses: {
      /** @description 更新成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CustomerController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 删除成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  LeadController_findAll: {
    parameters: {
      query?: {
        /** @description 页码 */
        page?: number
        /** @description 每页条数 */
        pageSize?: number
        /** @description 关键字（名称/联系人/电话/公司） */
        keyword?: string
        /** @description 状态 */
        status?: 'PENDING' | 'FOLLOWING' | 'CONVERTED' | 'INVALID'
        /** @description 线索池类型 */
        poolType?: 'MINE' | 'PUBLIC' | 'TEAM'
        /** @description 负责人ID */
        ownerId?: string
        /** @description 所属区域 */
        region?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回分页线索列表 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  LeadController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateLeadDto']
      }
    }
    responses: {
      /** @description 创建成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  LeadController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回线索详情及跟进记录 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  LeadController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateLeadDto']
      }
    }
    responses: {
      /** @description 更新成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  LeadController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 删除成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  IntentionController_findAll: {
    parameters: {
      query?: {
        /** @description 页码 */
        page?: number
        /** @description 每页条数 */
        pageSize?: number
        /** @description 关键字（客户名称/项目名称） */
        keyword?: string
        /** @description 客户ID */
        customerId?: string
        /** @description 负责人ID */
        ownerId?: string
        /** @description 状态 */
        status?: 'ACTIVE' | 'WON' | 'LOST' | 'STALLED'
        /** @description 所处阶段 */
        stage?: 'INITIAL' | 'NEGOTIATION' | 'QUOTATION' | 'CONTRACT' | 'WON'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回分页意向列表 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  IntentionController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateIntentionDto']
      }
    }
    responses: {
      /** @description 创建成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  IntentionController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回意向详情及阶段记录 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  IntentionController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateIntentionDto']
      }
    }
    responses: {
      /** @description 更新成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  IntentionController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 删除成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  EquipmentController_findAll: {
    parameters: {
      query?: {
        /** @description 页码 */
        page?: number
        /** @description 每页条数 */
        pageSize?: number
        /** @description 关键字（设备名称/编码/序列号） */
        keyword?: string
        /** @description 客户ID */
        customerId?: string
        /** @description 产品ID */
        productId?: string
        /** @description 负责人ID */
        ownerId?: string
        /** @description 状态 */
        status?: 'RUNNING' | 'MAINTAINING' | 'SCRAPPED'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回分页设备列表 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  EquipmentController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateEquipmentDto']
      }
    }
    responses: {
      /** @description 创建成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  EquipmentController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回设备详情 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  EquipmentController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateEquipmentDto']
      }
    }
    responses: {
      /** @description 更新成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  EquipmentController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 删除成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TicketController_findAll: {
    parameters: {
      query?: {
        /** @description 页码 */
        page?: number
        /** @description 每页条数 */
        pageSize?: number
        /** @description 关键字（标题/内容） */
        keyword?: string
        /** @description 客户ID */
        customerId?: string
        /** @description 处理人ID */
        assigneeId?: string
        /** @description 状态 */
        status?: 'PENDING' | 'PROCESSING' | 'WAITING' | 'RESOLVED' | 'CLOSED'
        /** @description 优先级 */
        priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT'
        /** @description 类型 */
        type?: 'REPAIR' | 'MAINTENANCE' | 'CONSULT' | 'COMPLAINT'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回分页工单列表 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TicketController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTicketDto']
      }
    }
    responses: {
      /** @description 创建成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TicketController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回工单详情及处理记录 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TicketController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTicketDto']
      }
    }
    responses: {
      /** @description 更新成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TicketController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 删除成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TaskController_findAll: {
    parameters: {
      query?: {
        /** @description 页码 */
        page?: number
        /** @description 每页条数 */
        pageSize?: number
        /** @description 关键字（任务标题/内容） */
        keyword?: string
        /** @description 任务类型 */
        type?: 'TODO' | 'FOLLOW_UP' | 'APPROVAL' | 'REVIEW'
        /** @description 优先级 */
        priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT'
        /** @description 状态 */
        status?: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED'
        /** @description 标签页类型 */
        tabType?: 'my' | 'team' | 'collaboration' | 'overdue'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回分页任务列表 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TaskController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTaskDto']
      }
    }
    responses: {
      /** @description 创建成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TaskController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回任务详情 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TaskController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTaskDto']
      }
    }
    responses: {
      /** @description 更新成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  TaskController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 删除成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ApprovalController_findAll: {
    parameters: {
      query?: {
        /** @description 页码 */
        page?: number
        /** @description 每页条数 */
        pageSize?: number
        /** @description 关键字（标题/业务关键字） */
        keyword?: string
        /** @description 审批类型 */
        module?: 'leave' | 'expense' | 'contract' | 'discount' | 'purchase' | 'other'
        /** @description 状态 */
        status?: 'pending' | 'approved' | 'rejected' | 'withdrawn'
        /** @description 标签页类型 */
        tabType?: 'all' | 'pending' | 'approved' | 'cc' | 'initiated'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回分页审批列表 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ApprovalController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateApprovalDto']
      }
    }
    responses: {
      /** @description 创建成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ApprovalController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回审批详情 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ApprovalController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateApprovalDto']
      }
    }
    responses: {
      /** @description 更新成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  ApprovalController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 删除成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AppController_findAll: {
    parameters: {
      query?: {
        /** @description 页码 */
        page?: number
        /** @description 每页条数 */
        pageSize?: number
        /** @description 关键字（应用名称/编码） */
        keyword?: string
        /** @description 分类 */
        category?: 'PLATFORM' | 'BUSINESS' | 'PROCESS' | 'ANALYSIS' | 'SYSTEM'
        /** @description 状态 */
        status?: 'ACTIVE' | 'INACTIVE'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回应用列表 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AppController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAppDto']
      }
    }
    responses: {
      /** @description 创建成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AppController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回应用详情 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AppController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAppDto']
      }
    }
    responses: {
      /** @description 更新成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AppController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 删除成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
