/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['AppController_getHello']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['HealthController_check']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/files/upload': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['UploadController_uploadFile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/files/uploads': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['UploadController_uploadFiles']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 用户登录 */
    post: operations['AuthController_login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 当前登录用户信息 */
    get: operations['AuthController_profile']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询用户列表 */
    get: operations['UserController_findAll']
    put?: never
    /** 创建用户 */
    post: operations['UserController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询用户详情 */
    get: operations['UserController_findOne']
    /** 更新用户 */
    put: operations['UserController_update']
    post?: never
    /** 删除用户 */
    delete: operations['UserController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/customers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询客户列表 */
    get: operations['CustomerController_findAll']
    put?: never
    /** 创建客户 */
    post: operations['CustomerController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/customers/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询客户详情 */
    get: operations['CustomerController_findOne']
    /** 更新客户 */
    put: operations['CustomerController_update']
    post?: never
    /** 删除客户（软删除） */
    delete: operations['CustomerController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/leads': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询线索列表 */
    get: operations['LeadController_findAll']
    put?: never
    /** 创建线索 */
    post: operations['LeadController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/leads/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 查询线索详情 */
    get: operations['LeadController_findOne']
    /** 更新线索 */
    put: operations['LeadController_update']
    post?: never
    /** 删除线索 */
    delete: operations['LeadController_remove']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    LoginDto: {
      /** @description 用户名 */
      username: string
      /** @description 密码 */
      password: string
    }
    CreateUserDto: {
      /** @description 用户名 */
      username: string
      /** @description 密码 */
      password: string
      /** @description 姓名 */
      name: string
      /** @description 手机号 */
      phone?: string
      /** @description 邮箱 */
      email?: string
      /** @description 部门ID */
      departmentId?: string
      /** @description 角色ID数组 */
      roleIds?: string[]
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'ACTIVE' | 'INACTIVE'
    }
    UpdateUserDto: {
      /** @description 密码 */
      password?: string
      /** @description 姓名 */
      name?: string
      /** @description 手机号 */
      phone?: string
      /** @description 邮箱 */
      email?: string
      /** @description 部门ID */
      departmentId?: string
      /** @description 角色ID数组 */
      roleIds?: string[]
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'ACTIVE' | 'INACTIVE'
    }
    CreateCustomerDto: {
      /** @description 客户名称 */
      name: string
      /** @description 客户类型 */
      type: string
      /** @description 医院等级 */
      hospitalLevel?: string
      /**
       * @description 客户级别
       * @enum {string}
       */
      level?: 'STRATEGIC' | 'NORMAL'
      /** @description 健康评分 */
      healthScore?: number
      /** @description 所属区域 */
      region: string
      /** @description 区域ID */
      regionId?: string
      /** @description 地址信息 */
      address?: Record<string, never>
      /** @description 负责人ID */
      ownerId: string
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'POTENTIAL' | 'COOPERATING' | 'LOST'
      /** @description 标签数组 */
      tags?: string[]
      /** @description 来源 */
      source?: string
    }
    UpdateCustomerDto: {
      /** @description 客户名称 */
      name?: string
      /** @description 客户类型 */
      type?: string
      /** @description 医院等级 */
      hospitalLevel?: string
      /**
       * @description 客户级别
       * @enum {string}
       */
      level?: 'STRATEGIC' | 'NORMAL'
      /** @description 健康评分 */
      healthScore?: number
      /** @description 所属区域 */
      region?: string
      /** @description 区域ID */
      regionId?: string
      /** @description 地址信息 */
      address?: Record<string, never>
      /** @description 负责人ID */
      ownerId?: string
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'POTENTIAL' | 'COOPERATING' | 'LOST'
      /** @description 标签数组 */
      tags?: string[]
      /** @description 来源 */
      source?: string
    }
    CreateLeadDto: {
      /** @description 线索名称 */
      name: string
      /** @description 线索来源 */
      source: string
      /** @description 来源明细 */
      sourceDetail?: string
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'PENDING' | 'FOLLOWING' | 'CONVERTED' | 'INVALID'
      /**
       * @description 线索池类型
       * @enum {string}
       */
      poolType?: 'MINE' | 'PUBLIC' | 'TEAM'
      /** @description 负责人ID */
      ownerId?: string
      /** @description 所属区域 */
      region?: string
      /** @description 联系人姓名 */
      contactName?: string
      /** @description 联系人电话 */
      contactPhone?: string
      /** @description 公司名称 */
      companyName?: string
      /** @description 需求描述 */
      demand?: string
      /** @description 预计金额 */
      estimatedAmount?: number
      /**
       * @description 意向等级
       * @enum {string}
       */
      intentionLevel?: 'HIGH' | 'MEDIUM' | 'LOW'
    }
    UpdateLeadDto: {
      /** @description 线索名称 */
      name?: string
      /** @description 线索来源 */
      source?: string
      /** @description 来源明细 */
      sourceDetail?: string
      /**
       * @description 状态
       * @enum {string}
       */
      status?: 'PENDING' | 'FOLLOWING' | 'CONVERTED' | 'INVALID'
      /**
       * @description 线索池类型
       * @enum {string}
       */
      poolType?: 'MINE' | 'PUBLIC' | 'TEAM'
      /** @description 负责人ID */
      ownerId?: string
      /** @description 所属区域 */
      region?: string
      /** @description 联系人姓名 */
      contactName?: string
      /** @description 联系人电话 */
      contactPhone?: string
      /** @description 公司名称 */
      companyName?: string
      /** @description 需求描述 */
      demand?: string
      /** @description 预计金额 */
      estimatedAmount?: number
      /**
       * @description 意向等级
       * @enum {string}
       */
      intentionLevel?: 'HIGH' | 'MEDIUM' | 'LOW'
      /** @description 转化客户ID */
      convertedCustomerId?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  HealthController_check: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UploadController_uploadFile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UploadController_uploadFiles: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_profile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_findAll: {
    parameters: {
      query: {
        page: number
        pageSize: number
        keyword: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserDto']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CustomerController_findAll: {
    parameters: {
      query?: {
        /** @description 页码 */
        page?: number
        /** @description 每页条数 */
        pageSize?: number
        /** @description 关键字（名称/标签） */
        keyword?: string
        /** @description 状态 */
        status?: 'POTENTIAL' | 'COOPERATING' | 'LOST'
        /** @description 客户级别 */
        level?: 'STRATEGIC' | 'NORMAL'
        /** @description 区域ID */
        regionId?: string
        /** @description 负责人ID */
        ownerId?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回分页客户列表 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CustomerController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCustomerDto']
      }
    }
    responses: {
      /** @description 创建成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CustomerController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 返回客户详情及关联数据 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CustomerController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCustomerDto']
      }
    }
    responses: {
      /** @description 更新成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CustomerController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 删除成功 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  LeadController_findAll: {
    parameters: {
      query: {
        page: number
        pageSize: number
        keyword: string
        status: string
        poolType: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  LeadController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateLeadDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  LeadController_findOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  LeadController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateLeadDto']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  LeadController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
